### ISSUE TITLE
How do I install this when NOT running Neo4J as a desktop?

### ISSUE THREAD

**Issue by crichey** [kvegter/dbreportapp#2]
We run and install Neo4J as a server, typically on Linux. How do I configure and install this when I don't ever have Desktop installed? I know how to turn on query logging but how do I install and run this?

Thanks!

**Comment by kvegter** [comment]
A bit late, I will take it. It can run standalone by just get a copy from this repository and open index.html in the browser.
I will add a clean zip in the releases for the next release
